<a href="https://colab.research.google.com/github/deepiskp-99/DSA_Python_CaseStudy/blob/main/Numpy_Casestudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Create a NumPy array with values from 10 to 49 (inclusive).**

**● Reshape it into a 4x10 matrix.**

**● Then extract the last column from the reshaped matrix,**

In [ ]:
import numpy as np

arr = np.arange(10, 50)
print(arr)

matrix = arr.reshape(4, 10)
print(matrix)

last_col = matrix[:, -1]
print(last_col)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[19 29 39 49]


**2. Create two 3×3 matrices:**

**One filled with all 5s , One with values from 1 to 9**

**● Add the two matrices**

**● Multiply them element-wise**

**● Then find the transpose of the result**


In [ ]:
A = np.full((3,3),5)
B = np.arange(1,10).reshape(3,3)
C = A+B
Mul = A*B
print("A = ",A)
print("B = ",B)
print("C = ",C)
print("Multipied ans =",Mul)
np.transpose(Mul)

A =  [[5 5 5]
 [5 5 5]
 [5 5 5]]
B =  [[1 2 3]
 [4 5 6]
 [7 8 9]]
C =  [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
Multipied ans = [[ 5 10 15]
 [20 25 30]
 [35 40 45]]


array([[ 5, 20, 35],
       [10, 25, 40],
       [15, 30, 45]])

**3. Create a NumPy array of 15 random integers between 10 and 100.**

**● Replace all values greater than 50 with -1.**

**● Count how many values were replaced.**


In [ ]:
arr = np.random.randint(10,101,size=15)
print("Original Array:",arr)

replaced_arr = np.where(arr > 50, -1, arr)
print("Modified Array:",replaced_arr)

count_replaced = np.sum(arr > 50)
print("Count of replaced values:",count_replaced)

Original Array: [11 76 25 77 41 95 54 43 38 83 67 67 93 54 19]
Modified Array: [11 -1 25 -1 41 -1 -1 43 38 -1 -1 -1 -1 -1 19]
Count of replaced values: 9


**4. Generate a 5×4 array with random values between 0 and 1 (float).**

**● Find the row with the maximum sum of values.**

**● Normalize each row using the formula:**

**x nor = x - min/max - min**

In [ ]:
ar = np.random.rand(5,4)
print("Array:",ar)

row_sum = np.sum(ar, axis=1)
max_row_index = np.argmax(row_sum)
print("Row with maximum sum:",max_row_index)

normal_arr = (ar - np.mean(ar)) / np.std(ar)
print("Normalized Array:",normal_arr)

Array: [[0.95501223 0.92664957 0.27051181 0.6253748 ]
 [0.96622428 0.77967406 0.54830953 0.04684245]
 [0.13007493 0.49998372 0.7994912  0.39964985]
 [0.13500007 0.99345407 0.14579401 0.72458238]
 [0.74389742 0.17221535 0.03380701 0.53470519]]
Row with maximum sum: 0
Normalized Array: [[ 1.32941258  1.2424228  -0.76998631  0.31839719]
 [ 1.36380054  0.79164117  0.08203396 -1.45599205]
 [-1.20071363 -0.06618386  0.85242139 -0.37391313]
 [-1.18560799  1.44731575 -1.15250241  0.62267208]
 [ 0.68191234 -1.07146674 -1.49597242  0.04030873]]


**5. arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])**

**● Find all unique elements**

**● Find the duplicates (elements that appear more than once)**

In [ ]:
arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
unique_elements = np.unique(arr)
print("Unique element is:",unique_elements)

unique, counts = np.unique(arr, return_counts=True)

duplicates = unique[counts > 1]
print("Duplicate is:",duplicates)

Unique element is: [1 3 5 7 9]
Duplicate is: [1 3 5]


**6.Create a 6×6 NumPy array with values from 1 to 36.**

**● Extract the middle 4×4 submatrix.**

**● Then extract all even numbers from this submatrix.**


In [ ]:
arr = np.arange(1, 37).reshape(6, 6)
print(arr)

submatrix = arr[1:5, 1:5]
print("Submatrix is:",submatrix)

even = submatrix[submatrix % 2 == 0]
print("Even number is:",even)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Submatrix is: [[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]
Even number is: [ 8 10 14 16 20 22 26 28]


**7. Generate an array of shape (3, 4) with values from 0 to 11.**

**● Reshape it to (2, 6)**

**● Then flatten it into a 1D array**

**● Convert the 1D array back to shape (4, 3)**

In [ ]:
arr = np.arange(0,12).reshape(3, 4)
print("Array is:\n",arr)

arr2 = arr.reshape(2, 6)
print("Reshaped array is:\n",arr2)

flat = arr2.flatten()
print("Flattened is :\n", flat)

arr3 = flat.reshape(4, 3)
print("Reshaped (4x3):\n", arr3)

Array is:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped array is:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Flattened is :
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped (4x3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


**8 . Create an array: a = np.array([[1, 2], [3, 4]])**

**● Append a new row [5, 6]**

**● Then append a new column [7, 8, 9]**


In [ ]:
a = np.array([[1, 2], [3, 4]])
a = np.vstack([a, [5, 6]])
print("After adding row:\n",a)

a = np.column_stack([a, [7, 8, 9]])
print("After adding column:\n",a)

After adding row:
 [[1 2]
 [3 4]
 [5 6]]
After adding column:
 [[1 2 7]
 [3 4 8]
 [5 6 9]]


**9.a = np.array([1, 2, 3])**

**b = np.array([4, 5, 6])**

**c = np.array([7, 8, 9])**

**● Join them into a single array**

**● Reshape the result into a 3×3 matrix**

**● Extract the diagonal elements**


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

joined = np.concatenate([a, b, c])
print("Joined array:", joined)

matrix = joined.reshape(3, 3)
print("3x3 Matrix:", matrix)

diag = np.diag(matrix)
print("\nDiagonal elements:", diag)

Joined array: [1 2 3 4 5 6 7 8 9]
3x3 Matrix: [[1 2 3]
 [4 5 6]
 [7 8 9]]

Diagonal elements: [1 5 9]


**10. Create a NumPy array of integers from 1 to 20.**

● **Extract all values that are divisible by 3 or 5.**

● **Count how many such values exist**

In [2]:
import numpy as np
arr = np.arange(1, 21)
print("Array:", arr)

divisible = arr[(arr % 3 == 0) | (arr % 5 == 0)]
print("Divisible by 3 or 5:", divisible)

count = divisible.size
print("Count:", count)

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Divisible by 3 or 5: [ 3  5  6  9 10 12 15 18 20]
Count: 9
